export const appConstants = {
    firstname: "firstname",
    firstnameLength: "firstnameLength",
    fathersName: "fathersName",
    sirname: "sirname",
    sirnameLength: "sirnameLength",
    mobileNumber: "mobileNumber",
    mobileNumberPattern:"mobileNumberPattern",
    email: "email",
    emailPattern: "emailPattern",
    password: "password",
    passwordLength:"passwordLength",
    cpassword: "cpassword",
    cpasswordMatch: "cpasswordMatch",
    gender: "gender",
    maritalStatus: "maritalStatus",
    birthDate:"birthDate",
    birthDateAgeDiff:"birthDateAgeDiff",
    birthTime:"birthTime",
    birthTime2:"birthTime2",
    birthTime3:"birthTime3",
    height:"height",
    properVillage:"properVillage",
    nickName:"nickName",
    birthDate:"birthDate",
    resident:"resident",
    residentOf:"residentOf",
    caste:"caste",
    gotra:"gotra",
    relatives:"relatives",
    annualIncome:"annualIncome",
    dad:"dad",
    mother:"mother",
    handicapped:"handicapped",
    handicappedDetails:"handicappedDetails",
    education:"education",
    educDetails:"educDetails",
    business:"business",
    businessDet:"businessDet",
    agediff:"agediff",
    cityPref:"cityPref",
    special:"special",
    profileReSubnit:"profileReSubnit",

    //select fields
}