export const mh_translations = {   
    translation: {
    nameTitle: "जर आपण अगोदर नाव नोंदणी केली असेल तर आपला १० अंकी मोबाईल नंबर किंवा इमेल आयडी आणि पासवर्ड टाकून लॉगिन करू शकता.",
    email:"इमेल आयडी",
    password:"पासवर्ड",
    cpassword:"पासवर्ड पुन्हा नमूद करा",
    confirmPassword:"पासवर्ड पुन्हा नमूद करा",
    remember:"लक्षात ठेवा",
    DontHaveAccount:"अकाउंट नसेल तरी नाव नोंदणी करा",
    forgotPassword: "पासवर्ड विसरलात ?",
    login: "लॉगिन करा",
    bhoiMangalVivah:"भोई मंगल विवाह",
    Copyright:"Copyright ©",
    nameRegister:"ज्यांच्यासाठी स्थळ पाहत आहात त्यांची माहिती भरून नाव नोंदणी करा. अगोदरच सदस्य आहात? लॉगिन करा.",
    firstname:"स्थळाचे नाव",
    fathersName:"वडिलांचे नाव",
    sirname:"आडनाव",
    mobileNumber:"मोबाईल नंबर ( १० अंकी )",
    maritalStatus:"स्थळाचा वैवाहिक दर्जा",
    unamrried:"अविवाहित", 
    widow:"विधवा",
    divorced:"घटस्पोटीत",
    widower: "विधुर",
    gender:'ज्यांच्यासाठी स्थळ पाहत आहेत त्यांचे लिंग',
    Male:"मुलगा",
    Female:"मुलगी",
    signup:"नोंदणी",
    rules:"मी सर्व नियम आणि अटी वाचल्या असून त्या मला मान्य आहेत.",
    ruleAgree:"आमच्या नियम आणि अटी मान्य करणे आवश्यक आहे.",
    fillAllTheFields:"कृपया सर्व आवश्यक फील्ड भरा"
    },
}